### ISSUE TITLE
Error building the package 

### ISSUE THREAD

**Issue by okasha55** [ros-melodic-arch/ros-melodic-realtime-tools#2] opened 2020-02-27 07:56 UTC
CMake Error at CMakeLists.txt:24 (target_link_libraries): Cannot specify link libraries for target "realtime_box_tests" which is not built by this project. 
can you help me with this error

**Comment by acxz** [comment] 2020-02-29 00:00
@okasha55 sadly this is an issue that has been around for a while, we have made progress on it recently tho. Closing this issue as it is a duplicate of #1 . Maybe you can follow the conversation and help us out.

**Closed as completed by acxz** 2020-02-29 00:00 UTC
